server:
  port: 8080

spring:
  #mysql数据源配置
  datasource:
    #url: jdbc:mysql://jtao0212.mysql.zhangbei.rds.aliyuncs.com:3306/jiantao??useUnicode=true&amp;characterEncoding=UTF-8
    #username: taojian
    #password: Tj6472899
    url: jdbc:mysql://localhost:3306/jiantao??useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: taojian
    driver-class-name: com.mysql.jdbc.Driver
  #redis配置
  redis:
    lettuce:
      pool:
        max-wait: 100
        max-active: 200
        max-idle: 10
        min-idle: -1
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 1000
#mybatis配置
mybatis:
  typeAliasesPackage: com.cmb.demo
  mapperLocations: classpath:mapper/*.xml
  #configLocation: classpath:/mybatis-config.xml